'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm12

    '''<summary>
    '''gvUsedCategoryList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvUsedCategoryList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblSelectedItemType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedItemType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvFilteredItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvFilteredItems As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblSelectedItemDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedItemDetails As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlEditUsedHardwareList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlEditUsedHardwareList As Global.System.Web.UI.WebControls.HyperLink
End Class
